image: microsoft/dotnet:latest
stages:
  - qa
  - build
  - test
  - deploy
  
codequality_preview:
  stage: qa
  script:
    - dotnet tool install --global dotnet-sonarscanner
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet sonarscanner begin /k:"akshay123" /d:sonar.host.url="http://35.243.243.55:9000" /d:sonar.login="c610771440c4a0fead6951cb3ea0a839b9ba173b"
    - dotnet build
    - dotnet sonarscanner end 



deploy:
  stage: deploy
  only:
    - master
  artifacts:
    paths:
      - publish/
  script:
    # The output path is relative to the position of the csproj-file
    - dotnet publish -c Release -o ../publish MyProject/MyProject.csproj
    
test:
  stage: test
  script:
    - dotnet test MyProject.Test/MyProject.Test.csproj

build:
  stage: build
  script:
    - dotnet build MyProject.Test/MyProject.Test.csproj
    
    
 